# Use a imagem oficial do ASP.NET Core
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

# Use a imagem oficial do SDK do .NET Core para compilação
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["wiki-blue-exorcist.csproj", "./"]
RUN dotnet restore "wiki-blue-exorcist.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "wiki-blue-exorcist.csproj" -c Release -o /app/build

# Publicar a aplicação
FROM build AS publish
RUN dotnet publish "wiki-blue-exorcist.csproj" -c Release -o /app/publish

# Etapa final para executar a aplicação
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "wiki-blue-exorcist.dll"]